### ISSUE TITLE
Improve the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m2-evaluacion-intermedia-irenegf83#1]
Really cool job @irenegf83  !!!

Here you have some tips to improve the exercise:

- [x] Move the feedback logic to a function an execute it on each click as you did with the counter logic.
- [x] You are writing many times "userFeedbackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'userFeedbackEl'?
- [x] Remove comments

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by irene-gomez** [comment]
Hi @nasivuela, the points you indicated to me are ready.
I've also made some additions like disable the button when you hit the number and put another button to play again.
I'll wait for your answer if I'm missing anything.

**Comment by nasivuela** [comment]
Sweet!!!!!

![](https://media.giphy.com/media/PApUlVfEFmZAQ/giphy.gif)
